# -*- coding: utf-8 -*-
"""PROYECTO_TESIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iligVQ8DYYYmPWybqowj90V-h-qn4YcE
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('fer2013.csv')

df.head()

df.info()
df['emotion'].value_counts()

import numpy as np
import matplotlib.pyplot as plt

pixels = df['pixels'][0]
image = np.array(pixels.split(), dtype='int')
image = image.reshape(48, 48)

plt.imshow(image, cmap='gray')
plt.show()

X = []
y = []

for i in range(len(df)):
    pixels = np.array(df['pixels'][i].split(), dtype='float32')
    pixels = pixels / 255.0  # normalizar
    X.append(pixels)
    y.append(df['emotion'][i])

X = np.array(X)
X = X.reshape(-1, 48, 48, 1)

y = np.array(y)




# amigo prueba esta version, es mas parametrizada y mas robusta para las imgs

# para sacar el cometario solo usa ctrl + shit + / seleccionando tood el cod

# IMG_SIZE    = 48
# CHANNELS    = 1
# PIXEL_COL   = 'pixels'
# LABEL_COL   = 'emotion'
# NORM_FACTOR = 255.0

# def load_fer_data(df, pixel_col=PIXEL_COL, label_col=LABEL_COL,
#                   img_size=IMG_SIZE, channels=CHANNELS, norm=NORM_FACTOR):
#     """
#     Carga y prepara datos del dataset FER.

#     Returns:
#         X: np.ndarray de forma (N, img_size, img_size, channels), float32, rango [0,1]
#         y: np.ndarray de etiquetas
#     """
#     pixels = (
#         df[pixel_col]
#         .str.split()
#         .apply(np.array)
#         .values
#     )
#     X = np.stack(pixels).astype('float32') / norm
#     X = X.reshape(-1, img_size, img_size, channels)
#     y = df[label_col].values
#     return X, y

# X, y = load_fer_data(df)

import tensorflow as tf
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, num_classes=7)

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(48,48,1)),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(7, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X, y, epochs=5, batch_size=64)

model.evaluate(X, y)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model.fit(X_train, y_train)

model.evaluate(X_test, y_test)

confianza = np.max(pred) * 100

print(f"Emoción: {emocion}")
print(f"Estrés: {estres}")
print(f"Confianza: {confianza:.2f}%")

model.fit(X_train, y_train)

model.save("/content/drive/MyDrive/modelo.keras")

import shutil

shutil.rmtree('/content/drive', ignore_errors=True)

from google.colab import drive
import shutil

# Ensure the mount point is clean before attempting to mount
shutil.rmtree('/content/drive', ignore_errors=True)

drive.mount('/content/drive', force_remount=True)

from google.colab import drive
drive.mount('/content/drive')

#SE LISTA LO QUE HAY EN EL DRIVE
import os
print(os.listdir("/content/drive/MyDrive/"))

#REALIZA EL GUARDADO DEL ENTRENAMIENTO REALIZADO
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# MODELOS ENTRENADOS
model.fit(X_train, y_train, epochs=5)

#SE GUARDA
model.save("/content/drive/MyDrive/modelo.keras")

import os
print(os.listdir("/content/drive/MyDrive/"))

from google.colab import drive
drive.mount('/content/drive')

#VERIFICACION DEL GUARDADO
import os

ruta_modelo = "/content/drive/MyDrive/modelo.keras"

if os.path.exists(ruta_modelo):
    print("Modelo guardado correctamente")
else:
    print("No se encontró el modelo")

from tensorflow.keras.models import load_model

model = load_model("/content/drive/MyDrive/modelo.keras")

#CARGAMOS EL MODELO ENTRENADO
from tensorflow.keras.models import load_model

model = load_model("/content/drive/MyDrive/modelo.keras")

#USAMOS LA CARPETA DONDE ESTAN LAS IMAGENES Y LO IMPORTAMOS EN EL MODELO ENTRENADO PARA EL ANALISIS
ruta = "/content/drive/MyDrive/IMAGENES/"

import os
import cv2
import numpy as np

#DETECTA EL ROSTRO
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
)

#ETIQUETAS
emociones = {
    0: "Enojo",
    1: "Disgusto",
    2: "Miedo",
    3: "Feliz",
    4: "Triste",
    5: "Sorpresa",
    6: "Neutral"
}

def nivel_estres(emocion_id):
    if emocion_id in [0, 1, 2]:
        return "ALTO"
    elif emocion_id == 4:
        return "MEDIO"
    else:
        return "BAJO"

#ANALISA LAS IMAGENES
for archivo in os.listdir(ruta):

    if archivo.lower().endswith((".jpg", ".png", ".jpeg")):
        path = os.path.join(ruta, archivo)

        img = cv2.imread(path)

        if img is None:
            print("Error con:", archivo)
            continue

        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        faces = face_cascade.detectMultiScale(gray, 1.3, 5)

        if len(faces) == 0:
            print(f"{archivo} → No se detectó rostro")
            continue

        for (x, y, w, h) in faces:
            rostro = gray[y:y+h, x:x+w]
            rostro = cv2.resize(rostro, (48,48))
            rostro = rostro / 255.0
            rostro = rostro.reshape(1,48,48,1)

            pred = model.predict(rostro)
            emocion_id = np.argmax(pred)

            emocion = emociones[emocion_id]
            estres = nivel_estres(emocion_id)

            print(f"{archivo} → {emocion} → {estres}")

import matplotlib.pyplot as plt

for archivo in os.listdir(ruta):

    if archivo.lower().endswith((".jpg", ".png", ".jpeg")):
        path = os.path.join(ruta, archivo)

        img = cv2.imread(path)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        faces = face_cascade.detectMultiScale(gray, 1.3, 5)

        for (x, y, w, h) in faces:
            rostro = gray[y:y+h, x:x+w]
            rostro = cv2.resize(rostro, (48,48))
            rostro = rostro / 255.0
            rostro = rostro.reshape(1,48,48,1)

            pred = model.predict(rostro)
            emocion_id = np.argmax(pred)

            emocion = emociones[emocion_id]
            estres = nivel_estres(emocion_id)

            #RESULTADO DE LAS IMAGENES
            plt.imshow(gray, cmap='gray')
            plt.title(f"{archivo} → {emocion} → {estres}")
            plt.axis('off')
            plt.show()

print(f"{archivo} → rostros detectados: {len(faces)}")

for (x, y, w, h) in faces:
    cv2.rectangle(img, (x,y), (x+w,y+h), (255,0,0), 2)

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title(archivo)
plt.show()

from sklearn.metrics import classification_report, confusion_matrix

import matplotlib.pyplot as plt

def convertir_estres(label):
    if label in [0,1,2]:
        return 2  # ALTO
    elif label == 4:
        return 1  # MEDIO
    else:
        return 0  # BAJO

y_original = df['emotion'].values
y_estres = np.array([convertir_estres(y_label) for y_label in y_original])

import tensorflow as tf
tf.keras.layers.Dense(3, activation='softmax')

from sklearn.metrics import classification_report
import numpy as np

# Convert one-hot encoded y_test to class labels
y_true = np.argmax(y_test, axis=1)

# Predict probabilities for X_test
y_pred_proba = model.predict(X_test)

# Convert predicted probabilities to class labels
y_pred = np.argmax(y_pred_proba, axis=1)

print(classification_report(y_true, y_pred))

resultados = []
resultados.append([archivo, estres])

import pandas as pd

df = pd.DataFrame(resultados, columns=["Imagen","Estres"])

print(df["Estres"].value_counts())

df["Estres"].value_counts().plot(kind='bar')

"""**2do metodo**"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(rescale=1./255)

train = datagen.flow_from_directory(
    "/content/drive/MyDrive/IMAGENES",
    target_size=(48,48),
    color_mode="grayscale",
    class_mode="categorical"
)

import os
print(os.listdir('/content/drive/MyDrive/'))

ruta = "/content/drive/MyDrive/IMAGENES/Angry/"

def convertir_estres(clase):
    if clase in ["angry", "fear", "disgust"]:
        return 2  # ALTO
    elif clase == "sad":
        return 1  # MEDIO
    else:
        return 0  # BAJO